version: "3.1"

services:
    localstack:
        image: localstack/localstack:latest
        networks:
            - localstack-net
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - EDGE_PORT=4566
            - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53
        ports:
            - "4566-4597:4566-4597"
        volumes:
            - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"

networks:
    localstack-net:
        external: false
        driver: bridge
        name: localstack-net
